on: push

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/setup-node@v3
      - run: npm install
      - run: node main.js
